load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_jvm_library(
    name = "wire-safe-enums-assertj",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//wire-safe-enums:wire-safe-enums",
        artifact("org.assertj:assertj-core")
    ]
)

kt_jvm_test(
    name = "wire-safe-enums-assertj-test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    main_class = "org.junit.platform.console.ConsoleLauncher",
    args = ["discover", "--select-package=com.egoodhall.wire.safe.enums.assertj"],
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":wire-safe-enums-assertj",
        "//wire-safe-enums:wire-safe-enums",
        artifact("org.assertj:assertj-core"),
        artifact("org.junit.jupiter:junit-jupiter-api"),
        artifact("org.junit.jupiter:junit-jupiter-params"),
        artifact("org.junit.platform:junit-platform-console")
    ]
)