module(name = 'egoodhall_tools', version = '1.0-SNAPSHOT')

bazel_dep(name = "contrib_rules_jvm", version = "0.30.0")
bazel_dep(name = "rules_jvm_external", version = "6.8")
bazel_dep(name = "rules_kotlin", version = "2.1.9")

# Kotlinc setup

# Kotlin toolchain setup

register_toolchains("//:kotlin_toolchain")

# Maven Dependencies

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

maven.install(
    lock_file = "//:maven_install.json"
)

maven.from_toml(
    libs_versions_toml = "//:libs.versions.toml",
)

use_repo(maven, "maven")