load("@rules_kotlin//kotlin:core.bzl", "kt_ksp_plugin")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_ksp_plugin(
    name = "moshi-kotlin-codegen",
    processor_class = "com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessorProvider",
    deps = [
        artifact("com.squareup.moshi:moshi"),
        artifact("com.squareup.moshi:moshi-kotlin"),
        artifact("com.squareup.moshi:moshi-kotlin-codegen"),
    ],
)

kt_jvm_library(
    name = "wire-safe-enums-moshi",
    srcs = glob(["*.kt"]),
    visibility = ["//visibility:public"],
    plugins = [":moshi-kotlin-codegen"],
    deps = [
        "//wire-safe-enums/src/main/kotlin/com/egoodhall/wire/safe/enums:wire-safe-enums",
        artifact("org.jetbrains.kotlinx:kotlinx-serialization-json"),
        artifact("com.fasterxml.jackson.module:jackson-module-kotlin")
    ]
)
