load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_jvm_library(
    name = "wire-safe-enums-kotlinx",
    srcs = glob(["*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//wire-safe-enums/src/main/kotlin/com/egoodhall/wire/safe/enums:wire-safe-enums",
        artifact("org.jetbrains.kotlinx:kotlinx-serialization-json"),
        artifact("com.fasterxml.jackson.module:jackson-module-kotlin")
    ]
)
