load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_jvm_test(
    name = "wire-safe-enums-jackson-test",
    srcs = glob(["*.kt"]),
    main_class = "org.junit.platform.console.ConsoleLauncher",
    args = ["discover", "--select-package=com.egoodhall.wire.safe.enums.jackson"],
    runtime_deps = JUNIT5_DEPS,
    deps = [
    		"//wire-safe-enums-jackson/src/main/kotlin/com/egoodhall/wire/safe/enums/jackson:wire-safe-enums-jackson",
        "//wire-safe-enums/src/main/kotlin/com/egoodhall/wire/safe/enums:wire-safe-enums",
        "//wire-safe-enums-assertj/src/main/kotlin/com/egoodhall/wire/safe/enums/assertj:wire-safe-enums-assertj",
        artifact("com.fasterxml.jackson.core:jackson-annotations"),
        artifact("com.fasterxml.jackson.core:jackson-databind"),
        artifact("com.fasterxml.jackson.module:jackson-module-kotlin"),
        artifact("org.assertj:assertj-core"),
        artifact("org.junit.jupiter:junit-jupiter-api"),
        artifact("org.junit.jupiter:junit-jupiter-params"),
        artifact("org.junit.platform:junit-platform-console")
    ]
)
