load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS")
load("@rules_kotlin//kotlin:core.bzl", "kt_ksp_plugin")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_jvm_test(
    name = "wire-safe-enums-moshi-test",
    srcs = glob(["*.kt"]),
    main_class = "org.junit.platform.console.ConsoleLauncher",
    args = ["discover", "--select-package=com.egoodhall.wire.safe.enums.moshi"],
    runtime_deps = JUNIT5_DEPS,
    deps = [
        "//wire-safe-enums-moshi/src/main/kotlin/com/egoodhall/wire/safe/enums/moshi:wire-safe-enums-moshi",
        "//wire-safe-enums/src/main/kotlin/com/egoodhall/wire/safe/enums:wire-safe-enums",
        "//wire-safe-enums-assertj/src/main/kotlin/com/egoodhall/wire/safe/enums/assertj:wire-safe-enums-assertj",
        artifact("com.squareup.moshi:moshi"),
        artifact("com.squareup.moshi:moshi-kotlin"),
        artifact("org.assertj:assertj-core"),
        artifact("org.junit.jupiter:junit-jupiter-api"),
        artifact("org.junit.jupiter:junit-jupiter-params"),
        artifact("org.junit.platform:junit-platform-console")
    ]
)
