name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Bazelisk
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run build
        id: build
        run: bazelisk build --logging=6 //...

      - name: Run tests
        id: test
        run: bazelisk test --logging=6 //...

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: failure() && steps.test.outcome == 'failure'
        with:
          name: test-logs
          path: bazel-testlogs/**/test.log
          compression-level: 9
          retention-days: 7
