name: CI/CD

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**/*'
      - '*.md'
      - '.gitignore'
  release:
    types:
    - published

jobs:
  cicd:
    runs-on: ubuntu-latest
    if: >-
      ${{
      (github.event_name == 'release' && github.event.action == 'published') ||
      (github.event_name == 'push')
      }}
    steps:
    -
      name: Validate release version
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      shell: python
      run: | 
        import os, re
        version = os.environ["version"]
        semver = r"^\d+\.\d+\.\d+(?:-[a-zA-Z0-9]+)*$"
        assert re.compile(semver).match(version)
      env:
        version: ${{ github.ref_name }}
    -
      name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    -
      name: Set up mise
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
    -
      name: Export JAVA_HOME from mise
      run: echo "JAVA_HOME=$(mise where java)" >> "$GITHUB_ENV"
    -
      name: Set up Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    -
      name: Spotless
      run: ./gradlew spotlessCheck
    -
      name: Detekt
      run: ./gradlew detekt
    -
      name: Build
      run: ./gradlew build
    -
      name: Publish artifacts
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      run: >-
        ./gradlew
        generatePomFileForMavenPublication
        generateMetadataFileForMavenPublication
        signMavenPublication
        publishAllPublicationsToCentralStagingRepository
        promoteStagedMavenArtifactsToCentralRepository
        -Pversion=${{ github.ref_name }}
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_NAMESPACE: ${{ secrets.OSSRH_NAMESPACE }}
