name: Publish Release

on:
  release:
    types:
    - published

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Validate release version
      shell: python
      run: | 
        import os, re
        version = os.environ["version"]
        semver = r"^\d+\.\d+\.\d+(?:-[a-zA-Z0-9]+)*$"
        assert re.compile(semver).match(version)
      env:
        version: ${{ github.ref_name }}
    -
      name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    -
      name: Set up JDK 25
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'gradle'
    -
      name: Set up Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    -
      name: Check formatting
      run: ./gradlew spotlessCheck
    -
      name: Build and Test
      run: ./gradlew build test
    -
      name: Publish Artifacts to Maven Central
      run: >-
        ./gradlew
        publishAllPublicationsToCentralStagingRepository
        -Pversion=${{ github.ref_name }}
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    -
      name: Promote Maven Central Artifacts from Staging
      shell: bash
      run: >-
        ./gradlew
        promoteStagedMavenArtifactsToCentralRepository
        -Pversion=${{ github.ref_name }}
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    -
      name: Publish Artifacts to GitHub Packages
      run: ./gradlew publishAllPublicationsToGithubPackagesRepository -Pversion=${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
