name: Publish Release

on:
  release:
    types:
    - created
    - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Validate release version
      shell: python
      run: | 
        import re
        import os
        re.compile("^\d+\.\d+\.\d+(?:-[a-zA-Z0-9]+)*$").match(os.environ["version"])
      env:
        version: ${{ github.ref_name }}
    -
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'gradle'
    -
      name: Publish
      run: ./gradlew publish -Pversion=${{ github.ref_name }}
