name: Publish Release

on:
  release:
    types:
    - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Validate release version
      shell: python
      run: | 
        import os, re
        version = os.environ["version"]
        semver = r"^\d+\.\d+\.\d+(?:-[a-zA-Z0-9]+)*$"
        assert re.compile(semver).match(version)
      env:
        version: ${{ github.ref_name }}
    -
      name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    -
      name: Set up JDK 25
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'gradle'
    -
      name: Set up Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    -
      name: Build and Publish
      run: >-
        ./gradlew
        spotlessCheck
        build
        test
        generatePomFileForMavenPublication
        generateMetadataFileForMavenPublication
        signMavenPublication
        publishAllPublicationsToCentralStagingRepository
        promoteStagedMavenArtifactsToCentralRepository
        -Pversion=${{ github.ref_name }}
      env:
        RELEASE: true
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_NAMESPACE: ${{ secrets.OSSRH_NAMESPACE }}
